//===--- SILGenBuiltinConformance.cpp - SIL for builtin conformances ------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2014 - 2017 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

#include "SpecializedEmitter.h"

#include "ArgumentSource.h"
#include "Cleanup.h"
#include "Initialization.h"
#include "LValue.h"
#include "RValue.h"
#include "SILGenFunction.h"
#include "Scope.h"
#include "swift/AST/ASTContext.h"
#include "swift/AST/Builtins.h"
#include "swift/AST/DiagnosticsSIL.h"
#include "swift/AST/FileUnit.h"
#include "swift/AST/GenericEnvironment.h"
#include "swift/AST/Module.h"
#include "swift/AST/ProtocolConformance.h"
#include "swift/SIL/SILArgument.h"
#include "swift/SIL/SILUndef.h"

using namespace swift;
using namespace Lowering;

void BuiltinWitnessEmitter::emitBuiltinConformanceBody(
    SILGenFunction &SGF, BuiltinProtocolConformance *conformance) {
  auto knownKind = conformance->getProtocol()->getKnownProtocolKind();
  assert(knownKind.hasValue() && "Not a known protocol kind?");

  auto &ctx = SGF.getASTContext();

  auto loc = RegularLocation::getAutoGeneratedLocation();
  SmallVector<ManagedValue, 8> params;
  SGF.collectThunkParams(loc, params);

  switch (*knownKind) {
  case KnownProtocolKind::Equatable: {
    FullExpr scope(SGF.Cleanups, CleanupLocation(loc));

    assert(params.size() == 3);
    auto ptrType = SILType::getRawPointerType(SGF.getASTContext());
    auto i1Ty = SILType::getBuiltinIntegerType(1, SGF.getASTContext());

    auto boolTy = SGF.getASTContext().getBoolType()->getCanonicalType();

    auto lhsLoad = SGF.B.createLoadBorrow(loc, params[0]);
    auto rhsLoad = SGF.B.createLoadBorrow(loc, params[1]);

    auto lhsPtr = SGF.B.createUncheckedBitCast(loc, lhsLoad, ptrType);
    auto rhsPtr = SGF.B.createUncheckedBitCast(loc, rhsLoad, ptrType);

    SILValue returnVal = SGF.B.createBuiltinBinaryFunction(
        loc, "cmp_eq", ptrType, i1Ty,
        {std::move(lhsPtr).forward(SGF), std::move(rhsPtr).forward(SGF)});

    auto *returnBoolVal = SGF.B.createStruct(
        loc, SILType::getPrimitiveObjectType(boolTy), returnVal);
    SGF.emitManagedRValueWithCleanup(returnBoolVal);

    scope.pop();
    SGF.B.createReturn(loc, returnBoolVal);
  } break;
  case KnownProtocolKind::Hashable: {
    FullExpr scope(SGF.Cleanups, CleanupLocation(loc));

    auto wordTy = SILType::getBuiltinWordType(ctx);

    auto hasherType = SGF.F.getSelfArgument()->getType().getASTType();
    auto hasherDecl = hasherType.getNominalOrBoundGenericNominal();
    assert(hasherDecl);
    auto allCombines = hasherDecl->lookupDirect(ctx.Id_combine);
    assert(!allCombines.empty());

    auto decl = llvm::find_if(allCombines, [&](ValueDecl *decl) {
      auto *FD = dyn_cast<FuncDecl>(decl);
      if (!FD || FD->isStatic() || FD->getParameters()->size() != 1)
        return false;

      auto *firstParam = FD->getParameters()->get(0);
      if (!firstParam->getType()->isEqual(ctx.getUIntType()))
        return false;

      return true;
    });
    assert(decl != allCombines.end());
    auto *combine = cast<FuncDecl>(*decl);

    auto *ptrToInt = SGF.B.createBuiltin(
        loc, ctx.getIdentifier(getBuiltinName(BuiltinValueKind::PtrToInt)),
        wordTy, SubstitutionMap(), {params[1].borrow(SGF, loc).forward(SGF)});

    auto *intVal = SGF.B.createStruct(
        loc, SGF.getLoweredType(ctx.getUIntType()), {ptrToInt});

    auto hasherSource = ArgumentSource(
        loc, LValue::forAddress(SGFAccessKind::ReadWrite, params[1], None,
                                AbstractionPattern(hasherType), hasherType));
    auto args = PreparedArguments({AnyFunctionType::Param(ctx.getUIntType())});
    args.add(loc, RValue(SGF, loc, ctx.getUIntType()->getCanonicalType(),
                         ManagedValue::forTrivialRValue(intVal)));

    SGF.emitApplyMethod(loc, combine, std::move(hasherSource), std::move(args),
                        SGFContext());

    scope.pop();
    SGF.B.createReturn(loc, SGF.emitEmptyTuple(loc));
  } break;
  default:
    llvm_unreachable("Unimplemented");
  }
}
